default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: social_journal_api_development

test:
  <<: *default
  database: social_journal_api_test

production:
  <<: *default
  database: social_journal_api_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
